TASK 1: Implement Linear Regression Algorithm on the given dataset

In [39]:
import numpy as np
import torch 


In [40]:
input=np.array([[73,67,43],[91,88,64],
               [87,134,58],[102,43,37],
               [69,96,70]],dtype='float32')

In [41]:
target=np.array([[56],[81],[119],
                [22],[103]],dtype='float32')

In [42]:
x_data=torch.from_numpy(input)
x_data

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [43]:
y_data=torch.from_numpy(target)
y_data


tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])

In [44]:
w=torch.randn(1,3,requires_grad=True)
w

tensor([[ 2.8931, -1.2044, -1.1576]], requires_grad=True)

In [45]:
b=torch.randn(5,1,requires_grad=True)

In [46]:
model=x_data@w.t() + b
model

tensor([[ 79.2638],
        [ 82.0578],
        [ 22.9890],
        [199.2547],
        [  2.0896]], grad_fn=<AddBackward0>)

In [47]:
target

array([[ 56.],
       [ 81.],
       [119.],
       [ 22.],
       [103.]], dtype=float32)

In [48]:
target=torch.from_numpy(target)

In [49]:
diff=model-target

In [50]:
loss=torch.sum(diff*diff)/torch.numel(diff)
loss

tensor(10272.5137, grad_fn=<DivBackward0>)

In [51]:
loss.backward(retain_graph=True)

In [52]:
print(w)
print(w.grad)

tensor([[ 2.8931, -1.2044, -1.1576]], requires_grad=True)
tensor([[ 1823.4895, -5311.6631, -2002.3596]])


In [53]:
print(b)
print(b.grad)

tensor([[-1.4632],
        [-1.1437],
        [-0.1854],
        [-1.2220],
        [-0.8835]], requires_grad=True)
tensor([[  9.3055],
        [  0.4231],
        [-38.4044],
        [ 70.9019],
        [-40.3642]])


ADJUST WEIGHTS AND BIASES USING GRADIENT DESCENT

In [61]:
model=x_data@w.t() + b
print(model)  #Here model is predicions


tensor([[ 85.4409],
        [ 90.6506],
        [ 36.3749],
        [201.5832],
        [ 12.5757]], grad_fn=<AddBackward0>)


In [62]:
#finding loss using predictions(model) and target
diff=model-target
loss=torch.sum(diff*diff)/torch.numel(diff)
print(loss)

tensor(9642.6953, grad_fn=<DivBackward0>)


In [63]:
loss.backward(retain_graph=True)

In [64]:
print(w.grad)
print(b.grad)

tensor([[ 3166.8867, -3683.4492, -1037.5125]])
tensor([[ 11.7764],
        [  3.8602],
        [-33.0500],
        [ 71.8333],
        [-36.1697]])


In [65]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
    

In [66]:
print(w)
print(b)

tensor([[ 2.8250, -1.0613, -1.1072]], requires_grad=True)
tensor([[-1.4635],
        [-1.1438],
        [-0.1844],
        [-1.2241],
        [-0.8823]], requires_grad=True)


In [69]:
model=x_data@w.t() + b
diff=model-target
loss=torch.sum(diff*diff)/torch.numel(diff)
print(loss) # loss is reduced

tensor(9398.8984, grad_fn=<DivBackward0>)


TRAIN FOR MULTIPLE EPOCHS(100)

In [70]:
for i in range(100):
    model=x_data@w.t() + b
    diff=model-target
    loss=torch.sum(diff*diff)/torch.numel(diff)
    loss.backward(retain_graph=True)
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [71]:
model=x_data@w.t() + b
diff=model-target
loss=torch.sum(diff*diff)/torch.numel(diff)
print(loss)

tensor(893.0757, grad_fn=<DivBackward0>)


In [72]:
model #predictions

tensor([[ 66.0266],
        [ 79.2838],
        [110.4050],
        [ 75.4551],
        [ 65.1771]], grad_fn=<AddBackward0>)

In [73]:
target

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])

TASK 2: LINEAR REGRESSION USING PYTORCH

In [74]:
import numpy as np
import torch
import torch.nn as nn

In [77]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

In [78]:
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

In [79]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

DATASET AND DATALOADER

In [80]:
from torch.utils.data import TensorDataset

In [81]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [82]:
from torch.utils.data import DataLoader

In [83]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [85]:
for x, y in train_dl:
    print(x)
    print(y)
    break

tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]])
tensor([[103., 119.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 22.,  37.]])


In [86]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4619,  0.1736,  0.5170],
        [ 0.4268,  0.0601, -0.1763]], requires_grad=True)
Parameter containing:
tensor([-0.2904, -0.3568], requires_grad=True)


In [87]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.4619,  0.1736,  0.5170],
         [ 0.4268,  0.0601, -0.1763]], requires_grad=True),
 Parameter containing:
 tensor([-0.2904, -0.3568], requires_grad=True)]

In [143]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)

In [144]:
def modelpred(x):
  return x@w.t() + b

In [145]:
preds=modelpred(inputs)
preds

tensor([[ 60.8727,  -6.3265],
        [ 92.4930,  -7.9953],
        [104.8570,  38.0917],
        [ 31.0562, -45.4887],
        [112.8785,  12.0562],
        [ 60.8727,  -6.3265],
        [ 92.4930,  -7.9953],
        [104.8570,  38.0917],
        [ 31.0562, -45.4887],
        [112.8785,  12.0562],
        [ 60.8727,  -6.3265],
        [ 92.4930,  -7.9953],
        [104.8570,  38.0917],
        [ 31.0562, -45.4887],
        [112.8785,  12.0562]], grad_fn=<AddBackward0>)

In [146]:
# Import nn.functional
import torch.nn.functional as F

In [147]:
# Define loss function
loss_fn = F.mse_loss

In [148]:
def loss_func(i1,i2):
  diff=i1-i2
  return torch.sum(diff*diff)/torch.numel(diff)

In [149]:
loss=loss_func(preds,targets)
print(loss)

tensor(4549.0127, grad_fn=<DivBackward0>)


TRAIN THE MODEL


In [150]:
def fit(num_epochs, model, loss_fn):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = modelpred(xb)
            
            # 2. Calculate loss
            loss = loss_func(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            
            
    
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [151]:
fit(100,model,loss_fn)

Epoch [10/100], Loss: 3596.3665
Epoch [20/100], Loss: 4604.9531
Epoch [30/100], Loss: 4837.0752
Epoch [40/100], Loss: 4829.4580
Epoch [50/100], Loss: 4549.0127
Epoch [60/100], Loss: 5013.8286
Epoch [70/100], Loss: 4165.4468
Epoch [80/100], Loss: 3467.9370
Epoch [90/100], Loss: 4316.3184
Epoch [100/100], Loss: 4596.7642


In [152]:
preds=modelpred(inputs)
preds

tensor([[ 60.8727,  -6.3265],
        [ 92.4930,  -7.9953],
        [104.8570,  38.0917],
        [ 31.0562, -45.4887],
        [112.8785,  12.0562],
        [ 60.8727,  -6.3265],
        [ 92.4930,  -7.9953],
        [104.8570,  38.0917],
        [ 31.0562, -45.4887],
        [112.8785,  12.0562],
        [ 60.8727,  -6.3265],
        [ 92.4930,  -7.9953],
        [104.8570,  38.0917],
        [ 31.0562, -45.4887],
        [112.8785,  12.0562]], grad_fn=<AddBackward0>)

In [153]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])