Task:1

Exercise: Manually calculate output for the following cases and compare it
with system's output.

In [2]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [3]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny',
         'Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
      'Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
      'Yes','Yes','Yes','Yes','No']

In [4]:
le=preprocessing.LabelEncoder()

weather_encoded=le.fit_transform(weather)
print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [5]:
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print(temp_encoded)
print(label)


[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [6]:
features=tuple(zip(weather_encoded,temp_encoded))
print(features)

((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [7]:
model=MultinomialNB()
model.fit(features,label)

MultinomialNB()

1)Will you play if the temperature is 'Hot' and the weather is 'overcast'?

In [8]:
predicted=model.predict([[0,1]])
print(predicted)

[1]


2)Will you play if the temperature is 'Mild' and the weather is 'Sunny'?

In [9]:
predicted=model.predict([[2,2]])
print(predicted)

[1]


Task2:

In [10]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris=datasets.load_iris()

In [11]:
print("Features: ",iris.feature_names)
print("Labels: ",iris.target_names)
print("\nData Shape: ",iris.data.shape)
print("\nTarget Shape: ",iris.target.shape)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']

Data Shape:  (150, 4)

Target Shape:  (150,)


In [12]:
print("\nData type: ",type(iris.data))
newdata=iris.data[50:,:]
newtarget=iris.target[50:]
print(newdata.shape)
print(newtarget.shape)


Data type:  <class 'numpy.ndarray'>
(100, 4)
(100,)


In [13]:
from sklearn.model_selection import train_test_split
data_train,data_test,target_train,target_test=train_test_split(newdata,
        newtarget,test_size=0.30,random_state=5)

In [14]:
import numpy as np
gnb=GaussianNB()
gnb.fit(data_train,target_train)
target_pred=gnb.predict(data_test)

In [15]:
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.9


In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test,target_pred)

array([[16,  1],
       [ 2, 11]])

In [17]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precsion=precision_score(target_test,target_pred)
recall=recall_score(target_test,target_pred)

print('precision: {}',format(precsion))
print('recall: {}',format(recall))

precision: {} 0.8888888888888888
recall: {} 0.9411764705882353


TASK3:


In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [19]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

datasets=pd.read_csv('drive/MyDrive/Dataset2.csv')
print(datasets)
print(datasets.describe())

   Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N
       Outlook Temp Wind Humidity Class
count       14   14   14       14    14
unique       3    3    2        3     2
top          S    M    F   Normal     Y
freq         5    7    8        8    10


In [20]:
x=datasets.iloc[:,:-1].values
y=datasets.iloc[:,-1].values
print("\nInput: \n",x)
print("\nOutput: \n",y)


Input: 
 [['R' 'H' 'F' 'Normal']
 ['R' 'H' 'T' 'High']
 ['O' 'H' 'F' 'Normal']
 ['S' 'M' 'F' 'Normal']
 ['S' 'M' 'F' 'Normal']
 ['S' 'M' 'T' 'Low']
 ['O' 'C' 'T' 'Normal']
 ['R' 'C' 'F' 'Normal']
 ['R' 'C' 'F' 'Low']
 ['S' 'M' 'F' 'High']
 ['R' 'M' 'T' 'High']
 ['O' 'M' 'T' 'Low']
 ['O' 'H' 'F' 'Normal']
 ['S' 'M' 'T' 'Normal']]

Output: 
 ['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']


In [21]:
onehotencoder=OneHotEncoder()
x=onehotencoder.fit_transform(datasets.Outlook.values.reshape(-1,1)).toarray()
print(x)

[[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [22]:
dfOneHot=pd.DataFrame(x,columns=datasets.Outlook.unique().tolist())
df=pd.concat([datasets,dfOneHot],axis=1)
df=df.drop(['Outlook'],axis=1)
print(df)

   Temp Wind Humidity Class    R    O    S
0     H    F   Normal     N  0.0  1.0  0.0
1     H    T     High     N  0.0  1.0  0.0
2     H    F   Normal     Y  1.0  0.0  0.0
3     M    F   Normal     N  0.0  0.0  1.0
4     M    F   Normal     Y  0.0  0.0  1.0
5     M    T      Low     Y  0.0  0.0  1.0
6     C    T   Normal     Y  1.0  0.0  0.0
7     C    F   Normal     Y  0.0  1.0  0.0
8     C    F      Low     Y  0.0  1.0  0.0
9     M    F     High     Y  0.0  0.0  1.0
10    M    T     High     Y  0.0  1.0  0.0
11    M    T      Low     Y  1.0  0.0  0.0
12    H    F   Normal     Y  1.0  0.0  0.0
13    M    T   Normal     N  0.0  0.0  1.0


In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=10)


TASK 4:


In [24]:
from sklearn import datasets

wine = datasets.load_wine()
print(wine.feature_names)
print(wine.target_names)

newdata = wine.data[50:,:]
newtarget = wine.target[50:]

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
['class_0' 'class_1' 'class_2']


In [25]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(newdata, newtarget, test_size = 0.80, random_state = 87)



In [26]:
import numpy as np
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
print(target_pred)

[1 1 2 1 1 1 2 1 1 1 1 2 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 2 1 1 2 1 1 1
 2 2 1 2 2 2 1 2 1 2 1 1 2 2 1 2 2 2 2 1 1 1 1 2 2 1 1 2 1 1 1 1 2 2 1 1 2
 1 1 1 1 2 1 2 2 1 1 2 1 1 1 1 2 1 1 2 1 1 2 1 2 2 1 1 2 2]


In [27]:
from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9223300970873787


In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[ 0,  8,  0],
       [ 0, 57,  0],
       [ 0,  0, 38]])

In [29]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print("precision: ", precision)
print("recall: ", recall)

precision:  [0.         0.87692308 1.        ]
recall:  [0. 1. 1.]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
